# Generated by Django 4.1.5 on 2023-01-05 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('rooms', models.PositiveIntegerField(default=1)),
                ('floors', models.PositiveIntegerField()),
                ('parking_places', models.PositiveIntegerField()),
                ('restaurant_places', models.PositiveIntegerField()),
                ('has_wifi', models.BooleanField()),
                ('has_breakfast', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds', models.IntegerField()),
                ('has_terrace', models.BooleanField(default=True)),
                ('has_kitchen', models.BooleanField(default=True)),
                ('has_tv', models.BooleanField(default=True)),
                ('has_fridge', models.BooleanField(default=True)),
                ('floor_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('time_in_days', models.PositiveIntegerField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
        ),
    ]
