# Generated by Django 4.1.5 on 2023-04-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('accounts', '0003_alter_profile_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hotels',
            field=models.ManyToManyField(blank=True, to='hotels.hotel'),
        ),
    ]
