FROM python:3.10.9-buster

WORKDIR /usr/src/app

# Solve OS dependencies
RUN apt update 
RUN apt install -y gcc python3-dev build-essential libpq-dev	

# Copy project files
COPY backend/ebooking/ .

# Copy uWSGI config file
# COPY config/labmalware_uwsgi.ini /usr/src/app/labmalware_uwsgi.ini

# Copy entrypoint script 
COPY docker/entrypoint_dev_django.sh .

# Solve Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN sed -i -e 's/\r$//' entrypoint_dev_django.sh


ENTRYPOINT ["./docker/entrypoint_dev_django.sh"]
