# Generated by Django 4.1.5 on 2023-01-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(null=True, upload_to='hotel/'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='image',
            field=models.ImageField(null=True, upload_to='hotelroom/'),
        ),
    ]
