# Generated by Django 4.1.5 on 2023-01-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_image_hotelroom_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotel',
            table='hotel',
        ),
        migrations.AlterModelTable(
            name='hotelroom',
            table='hotelroom',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reservation',
        ),
    ]
