# Generated by Django 4.1.5 on 2023-01-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_hotel_table_alter_hotelroom_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotelRooms',
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='hotels.hotel'),
        ),
    ]
