# Generated by Django 4.1.5 on 2023-01-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_at', models.CharField(max_length=50)),
                ('ends_at', models.CharField(max_length=50)),
                ('time_in_days', models.PositiveIntegerField(null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('observations', models.CharField(max_length=500)),
                ('phone_no', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('hotelRoom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelroom')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
    ]
