# Generated by Django 4.1.5 on 2023-04-11 13:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_at', models.DateTimeField(default=datetime.datetime.now)),
                ('ends_at', models.DateTimeField(default=datetime.datetime.now)),
                ('time_in_days', models.PositiveIntegerField(null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('observations', models.CharField(max_length=500)),
                ('phone_no', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('In asteptare', 'In asteptare'), ('Confirmata', 'Confirmata'), ('Anulata', 'Anulata')], default='In asteptare', max_length=20)),
                ('hotelRoom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
    ]
