# Generated by Django 4.1.5 on 2023-01-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_time_in_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hotel',
        ),
    ]
